name: dandi_theme
description: "Dandi Theme Package."
publish_to: none
version: 0.0.1

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=3.16.9"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: 2.4.8
  flutter_gen_runner: 5.4.0

flutter_gen:
  output: lib/gen/
  line_length: 120
  colors:
    inputs:
      - assets/colors/colors.xml
flutter:
  assets:
    - assets/colors/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900