name: Deploy 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: self-hosted
    
    steps:
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./foo-1.0.0-osx.zip
          asset_name: foo-1.0.0-osx.zip
          asset_content_type: application/zip
